### ISSUE TITLE
Extension manager not activating

### ISSUE THREAD

**Issue by garrettseepersad** [sybrew/The-SEO-Framework-Extension-Manager#11]
Deactivated and deleted the old plugin and then uploaded the newly released version then activated the plugin.

I do not see the SEO functionality anywhere, which leads me to believe it was not successfully installed.

**Comment by sybrew** [comment]
Hi Garrett,

The Extension Manager is add-on software for [The SEO Framework](https://wordpress.org/plugins/autodescription/).
So, it needs to be active for the Extension Manager to work. 

With "the old plugin" I meant the [old Extension Manager from WordPress.org](https://wordpress.org/plugins/the-seo-framework-extension-manager/).

**Comment by sybrew** [comment]
Hi @garrettseepersad 

Are you still experiencing this issue? I haven't received any reports like yours from other users.

**Comment by garrettseepersad** [comment]
Hello sybrew,

The issue is resolved. I misinterpreted the instructions.

Thank you for following up on the issue,
Garrett

**Comment by sybrew** [comment]
I understand. I need to work on those 😄 Thanks for following up!
