### ISSUE TITLE
Title appearing twice - even with Title Fix Extension

### ISSUE THREAD

**Issue by royashgit** [sybrew/The-SEO-Framework-Extension-Manager#12]
We are using the popular X Theme and upgraded everything to their latest version. 

The title on every page and post appears twice, even when using the Title Fix extension. It appears once with the site name and then without.

<title>Awards \| Sport, ESPY Awards, July, Los Angeles, USA \| Site Name</title>
<title>Awards \| Sport, ESPY Awards, July, Los Angeles, USA</title>

Everything used to work fine when we were using a much older version of the SEO framework plus the old Title Fix Extension.

Any ideas on how to fix this?

many thanks
Andrew

**Comment by sybrew** [comment]
Hello!

The SEO Framework doesn't output title tags; it only modifies them. 
The Title Fix extension doesn't account for duplicated title tag issues, because they're absolute edge-cases.

With that, I suggest reaching out to Themeco. 

Before that, be sure to check your child theme's `header.php`. You should remove the `wp_title()` call, and let WordPress handle the title output from there. It's most likely a discrepancy around WordPress 4.4 support: https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/

Good luck!

**Comment by royashgit** [comment]
Thank you, I have tried removing their code but still the same problem persists. Is there any other calls I need to check? I haven't found any other instances of wp_title in the X theme code..

[if ( ! function_exists( 'x_wp_title' ) ) :
  function x_wp_title( $title ) {

    if ( is_front_page() ) {
      return get_bloginfo( 'name' ) . ' | ' . get_bloginfo( 'description' );
    } elseif ( is_feed() ) {
      return ' | RSS Feed';
    } else {
      return trim( $title ) . ' | ' . get_bloginfo( 'name' );
    }

  }
  add_filter( 'wp_title', 'x_wp_title' );
endif;](url)

**Comment by sybrew** [comment]
Cheers! That filter modifies the 2015 `wp_title` output. We're now in 2019, so I expect them to have that as a legacy feature&mdash;a fallback.

I recommend looking for outputting or generating calls, related to the title.
1.  `add_action( 'wp_head', ... );`
2. Anything `<title>`.

I also recommend reaching out to Themeco, because you're using a paid product I don't have access to nor have much knowledge about. I can only assume from here, which is not very useful.

**Comment by royashgit** [comment]
Hello, still nothing. I have contacted Themeco but their solution doesn't work either.. 

https://theme.co/apex/forum/t/title-output-seo-framework-conflict/61473/2

This is really puzzling :(

**Comment by sybrew** [comment]
Hello again! I understand this must be frustrating for you.

Their support staff didn't investigate the issue thoroughly and gave a standard reply. To clarify, it's not a conflict with The SEO Framework. If you'd deactivate TSF, the duplicated title tag will still be there.

Here's the problem, described in full:
> The (child-)theme (or another plugin) active on your site is adding a second title tag, next to the default WordPress title output.

The filter you've removed in the X Theme didn't cause this issue; it merely changes the contents of the problematic code.

I suggest looking through your plugin/theme files for extraneous title tag outputs. It'd look like:
```php
'<title>...</title>'
``` 

Where `...` can be anything. But, seeing as your filter-removal did something, it'd probably contain a `wp_title()` call.

I recommend using a deep code-search extension like included by default with VSCode, Atom, and Notepad++, and search for: `<title>`. 

If you're ready to give up, then I suggest hiring a developer or have a Themeco developer investigate.

Alternatively, the code below will patch it. It can be added to any plugin or theme. But, I don't recommend using it, it's a cloak that'll lead to problems down the road, it's not a cure.
```php
add_action( 'after_setup_theme`, function() {
	remove_theme_support( 'title-tag' ); // remove the correct title.
}, PHP_INT_MAX );
```

**Comment by royashgit** [comment]
Yes I have tried searching for <title> and wp_title but I got only that reference. You can have a look here: 

https://www.dropbox.com/s/ht3tk6165c6u5q0/x_new.zip?dl=0

**Comment by royashgit** [comment]
They are now saying, if I remove the code I mentioned in their thread, that everything should work fine, but it doesn't. I wonder what else could be wrong here.

**Comment by sybrew** [comment]
Hi @royashgit 

Thanks for sharing that code. I've inspected it, and they're abiding by the WordPress theming API. At least, the header output is as it should be.

This means that the issue does not lie with the X Theme.

There may be a plugin or child-theme active that outputs the extraneous title. I recommend deactivating plugins one by one until the problem disappears. With that, you should be able to find the erroneous plugin. Do make a backup, just in case.

**Comment by royashgit** [comment]
ok sorry my fault, there was a duplication in the child theme eventually! thanks for the help, as I managed to locate the error with your assistance ;)
