### ISSUE TITLE
Make articles structured data extendible via filter hook

### ISSUE THREAD

**Issue by zitrusblau** [sybrew/The-SEO-Framework-Extension-Manager#13]
Hey Sybre,

we need to adjust some structured data on custom post types, like adding content for recipes and such.
reading through the docs I supposed this was already possible. But it's only the 'type' that can be changed through the pm defaults. 

Best would be to have a filter hook in place at function _get_articles_json_output() in extensions/articles/trunk/inc/front.class.php

what do you think? would make life much easier as the LD-Script would not have to be created from scratch again or adjusted via JS after creation...

**Comment by sybrew** [comment]
Hi @zitrusblau 

Thanks for your suggestion. I also forwarded it here, where I explain how this can be achieved:
https://github.com/sybrew/the-seo-framework/issues/440#issuecomment-515422469

With that, we'd want to hook Articles into TSF's v3.4(+) Schema.org data and add to it, whereafter you can easily modify our input before it's converted into a script.

**Comment by zitrusblau** [comment]
that sounds really good. hope it won't take too long until 3.4 since otherwise we might need to built it ourselves due to timeline restrictions. we'll keep an eye the changelog.

**Comment by sybrew** [comment]
Given my history of dealing with major releases (ever since I aimed for 100% stability), this functionality may take up to 5 months before shedding light. Albeit, I do already have a template for building it.

**Comment by zitrusblau** [comment]
okay, thanks again for framing an estimated timeline. we'll rethink how we deal with this issue on our part then.

**Comment by sybrew** [comment]
More users are asking for this feature. I'm going to implement one straight into the extension for the time being. We'll see where the future brings us and may deprecate it later when the need be.

**Comment by zitrusblau** [comment]
Sounds good, thank you! Will keep an eye on it then.
