### ISSUE TITLE
Indexing: Page might not be indexed

### ISSUE THREAD

**Issue by EspressoT** [sybrew/The-SEO-Framework-Extension-Manager#18]
Hi, I have just installed the plugin and for my homepage I get "The robots meta tag does not allow indexing". However, my robots do not block my homepage...Any idea why? Website is www.espressotranslations.com

**Comment by sybrew** [comment]
Hello!

I can't find this tag either. That's odd. Is there anything you changed in the meantime that could've resolved this issue?

**Comment by EspressoT** [comment]
Hi,

I don't get it anymore on the English home page but I get it on the Italian
homepage...

Thanks,

Niki

*Niki Leiper *
Project Manager
Espresso Translations | ISO-Certified Language Services Provider
UK:  +44 203 488 1841  IT: +39 02 9475 0226
w: www.espressotranslations.com
<https://gml.email/v3.2/lt/38ba9c30108511eab2f60f28c261d250/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cDovL3d3dy5lc3ByZXNzb3RyYW5zbGF0aW9ucy5jb20v>
  e: info@espressotranslations.com
<https://gml.email/v3.2/lt/38ba9c31108511eab2f60f28c261d250/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cDovL21haWx0bzppbmZvQGVzcHJlc3NvdHJhbnNsYXRpb25zLmNvbQ>
<https://gml.email/v3.2/lt/38bac340108511eab2f60f28c261d250/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL0VzcHJlc3NvLVRyYW5zbGF0aW9ucy0zNzQzMzQ3NTkzMzU1NjUv>

<https://gml.email/v3.2/lt/38bac341108511eab2f60f28c261d250/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cHM6Ly90d2l0dGVyLmNvbS9FVF9UcmFuc2xhdGlvbnM>

<https://gml.email/v3.2/lt/38bac342108511eab2f60f28c261d250/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2NvbXBhbnkvZXNwcmVzc28tdHJhbnNsYXRpb25zLw>

IMPORTANT: The contents of this email and any attachments are confidential.
It is strictly forbidden to distribute, copy or share any part of this
message with any third party without written consent from the sender. If
you received this e-mail by mistake, please notify the sender immediately
and delete it from your system. *Please do not print this email unless it
is necessary. Every unprinted email helps the environment.*

**Comment by sybrew** [comment]
Ah, yes, I see it now. 

With WPML you can handle different meta for different languages of the same page.
When you edit the Italian page, you should see that the robots-indexing setting are set to "noindex". Change that, and it should be good.

Cheers!

**Comment by EspressoT** [comment]
It was actually set to default (index). I have now selected manually Index
and the blue I is gone.

Thank you very much for your efficiency.

Dan

*Danilo Coviello *
Project Manager
Espresso Translations | ISO-Certified Language Services Provider
UK:  +44 203 488 1841  IT: +39 02 9475 0226
w: www.espressotranslations.com
<https://gml.st/v3.2/lt/e0f14b5010e011ea811307748c4c9787/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cDovL3d3dy5lc3ByZXNzb3RyYW5zbGF0aW9ucy5jb20v>
  e: info@espressotranslations.com
<https://gml.st/v3.2/lt/e0f14b5110e011ea811307748c4c9787/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cDovL21haWx0bzppbmZvQGVzcHJlc3NvdHJhbnNsYXRpb25zLmNvbQ>
<https://gml.st/v3.2/lt/e0f14b5210e011ea811307748c4c9787/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL0VzcHJlc3NvLVRyYW5zbGF0aW9ucy0zNzQzMzQ3NTkzMzU1NjUv>

<https://gml.st/v3.2/lt/e0f1726010e011ea811307748c4c9787/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cHM6Ly90d2l0dGVyLmNvbS9FVF9UcmFuc2xhdGlvbnM>

<https://gml.st/v3.2/lt/e0f1726110e011ea811307748c4c9787/c29tZW9uZUB1bmtub3duLmNvbXx8aHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2NvbXBhbnkvZXNwcmVzc28tdHJhbnNsYXRpb25zLw>

IMPORTANT: The contents of this email and any attachments are confidential.
It is strictly forbidden to distribute, copy or share any part of this
message with any third party without written consent from the sender. If
you received this e-mail by mistake, please notify the sender immediately
and delete it from your system. *Please do not print this email unless it
is necessary. Every unprinted email helps the environment.*

**Comment by sybrew** [comment]
Cheers! I'm glad you found a workaround 😄
