### ISSUE TITLE
PHP Error: unserialize(): Error at offset 0 of 1 bytes

### ISSUE THREAD

**Issue by circuscode** [sybrew/The-SEO-Framework-Extension-Manager#29]
**Describe the bug**
Extension Manager throws the PHP error "PHP Error: unserialize(): Error at offset 0 of 1 bytes".

**To Reproduce**
This error occurs, if you open a post. Also custom post types are affected. On archive pages all is fine. I am not sure, but I think this error came with an recent update.

**Expected behavior**
No PHP error should come up.

**Screenshots**
<img width="1279" alt="2020-08-19_23-26-58" src="https://user-images.githubusercontent.com/20133480/90691725-171bc100-e274-11ea-82e0-9d7c8dcb284e.png">

**Additional context**
I have indicated the error with the plugin query monitor

**Comment by sybrew** [comment]
Hello!

Did you use the [Better Search Replace](https://wordpress.org/plugins/better-search-replace/) plugin? There's [a bug in that plugin that causes these errors to appear](https://wordpress.org/support/topic/php-notice-bsr_dbrecursive_unserialize_replace-the-script-tried-to-execut/#post-13115132), since it destroys serialized data.

I'm afraid there's no way around that--we cannot block that plugin from altering our data...

I think we should output a big fat non-dismissible warning whenever that plugin's detected. It caused too many issues.

**Comment by circuscode** [comment]
Hey.
Thank you for the fast answer.
Yes, you are right. Some weeks ago i had to replace a file path. :-(
But this was a one-time-usage of the plugin.
How can I fix that now? Are the tsf-post-meta destroyed or the tsf-settings? Can I fix that with some manipulations at the database? Would saving all posts again help? Or deinstall tsf with all settings and post-meta and install again? What is the best approach?
PHP-Errors are usually performance negativ, so I am willing to fix that.
Best Regards

**Comment by sybrew** [comment]
Hello!

This only affects the Extension Manager stored metadata. That data contains Articles and Focus metadata: The Article type and the Focus keywords.

I'm afraid the change is irreversible, and it's too far back to restore the database. Luckily, the erased data has only a minor impact: the Articles-type should fall back to the setting you entered for the post type.

Resaving the post (via the post editor, not via quick-edit) will resolve the error, but it won't restore your metadata.

I'm currently debugging their code to find the cause and might send a PR. But, this won't help you now 😞

**Comment by circuscode** [comment]
Hm...
I am not using the focus function. And the schema-article type is for all posts the same in my blog. Maybe this makes the thing easier? I could just erase the affected tsf-extension-manager-post-meta-entries, if I could identify them via key-name.

**Comment by sybrew** [comment]
I'm glad you didn't interact with the metadata; effectively, you've suffered no losses! 🥳 

Yes, you could just erase the data--it slipped my mind that [we have a KB article on that](https://kb.theseoframework.com/kb/data-stored-in-your-database/#em-post).
Add this code to your (child-)theme's `functions.php` file or a custom plugin, and visit the website once.
```php
add_action( 'admin_init', function() {
	delete_metadata( 'post', 0, '_tsfem-extension-post-meta', false, true );
	delete_metadata( 'term', 0, '_tsfem-extension-term-meta', false, true ); // This shouldn't be populated yet as of EM v2.4.0
} );
```

After a visit or two, you can delete the code. All errors should then be gone.

I also reported the issue in a manner that other users take notice, and provided a solution for DeliciousBrains: https://wordpress.org/support/topic/can-destroy-serialized-data/

**Comment by circuscode** [comment]
Great! This makes me happy!
I will try this out and post an update here, if it works.
Thank you very much for your support! :-)

**Comment by circuscode** [comment]
I can confirm it works. :-)
Thank you also for your effort regarding the plugin BSR. This is really not acceptable. With over 1 million installations and 4,5 stars it must be ensured that such cases do not happen.
