### ISSUE TITLE
Add image structure data so featured images are shown In google 

### ISSUE THREAD

**Issue by Solutiontales** [sybrew/The-SEO-Framework-Extension-Manager#32]
Under social data card add image structure data so images will be displayed in google results along with the url. If possible keep this separate from schema until all the schemas are available and their additnal data can be added

**Comment by sybrew** [comment]
Hello!

Google crawls anything that remotely resembles a URL--even from Open Graph meta. So, there's a good chance they'll discover those images after they parse your pages.

Moreover, we already provide [the structured data type for Articles](https://theseoframework.com/?p=2303), which I believe is exactly what you're proposing. For more information, please [refer to our KB article about structured data](https://kb.theseoframework.com/?p=58).
