### ISSUE TITLE
Allow Google Analytics 4 property for Cord Extension

### ISSUE THREAD

**Issue by v2theg** [sybrew/The-SEO-Framework-Extension-Manager#42]
I'm wondering about the possibility of saving a Google Analytics 4 property in the Cord extension and outputting the corresponding gtag.js code for it.

**Comment by sybrew** [comment]
Hello!

Since GA4 is imposed imminently, I've already marked this feature for the next major update of Extension Manager. 

Until then, I'm afraid there's no workaround other than (keep) using the reliable UA.
https://support.google.com/analytics/answer/9964640

**Comment by v2theg** [comment]
Hello,

Thank you for the info!
