### ISSUE TITLE
Wrong assets url on Windows

### ISSUE THREAD

**Issue by vralle** [sybrew/The-SEO-Framework-Extension-Manager#45]
**Describe the bug**
Error 403 when loading Focus extension scripts on OS Windows
The plugin incorrectly processes the base path to the plugin directory, which is why the paths for the scripts are incorrect.

**To Reproduce**
1. Activate Focus extension
2. Edit post.
3. See error in browser console

**Observed behavior**
Scripts is not found
Request URL: `https://localhost/wp-content/plugins/the-seo-framework-extension-manager/C:/site/wp/wp-content/plugins/the-seo-framework-extension-manager/extensions/essentials/focus/trunk/lib/js/tsfem-focus-inpost.js?ver=1.4.0`
Request Method: GET
Status Code: ERR_ABORTED 403

**Additional context**
Error in `extension_basename`:
https://github.com/sybrew/The-SEO-Framework-Extension-Manager/blob/1adbf22ccdc99465e9d658ddfd4cca67228cb4ed/inc/functions/internal.php#L37-L49
The function uses wp_normalize_path() (replaces backslashes with forward slashes).
Then the function uses DIRECTORY_SEPARATOR replacement at the end (when the path is already normalized and uses forward slashes, DIRECTORY_SEPARATOR is the backslash on Windows)
Fix: replace DIRECTORY_SEPARATOR with forward slash in trim. Trim after preg_replace() is superfluous.

**Comment by sybrew** [comment]
Hi Vitaliy! 

Thank you for opening this issue. I have a fix ready but didn't commit it yet.

This year's been hectic for me and slowed down the plugin's development. 
This month, however, a new update is planned.
