### ISSUE TITLE
PHP 8.0 installation using composer

### ISSUE THREAD

**Issue by bonakor** [sybrew/The-SEO-Framework-Extension-Manager#52]
**Describe the bug**
When I'm running composer install on a PHP 8 installation, Composer won't process because the extension requires PHP to go from 5.6 to 7. 

**To Reproduce**
1. Install PHP 8
2. Run composer install

Error is this:
`Problem 1
    - Root composer.json requires sybrew/the-seo-framework-extension-manager ^2.5.2 -> satisfiable by sybrew/the-seo-framework-extension-manager[2.5.2].
    - sybrew/the-seo-framework-extension-manager 2.5.2 requires php ^5.6 || ^7.0 -> your php version (8.0.10) does not satisfy that requirement.`

**Comment by sybrew** [comment]
Thanks for opening this issue.

I just changed the composer.json file to support all PHP versions TSF supports. Please note that Packagist is not aware of this change because it requires a tag/release to take effect. So, you may need to override that issue manually until I release a formal update.
