### ISSUE TITLE
Can't see how to install Extension Title -fix 

### ISSUE THREAD

**Issue by jimsax** [sybrew/The-SEO-Framework-Extension-Manager#53]
I have downloaded and The SEO Framework Extension Manager and on Title - Fix it states For your convenience, all packed into the Extension Manager. But I can't find any Extensions in Extensions Manager. Can you please advise.

**Comment by sybrew** [comment]
Hello!

You can learn how to install and activate Extension Manager: https://tsf.fyi/kb/install-em

To activate Title Fix, browse to SEO > Extension Manager in the sidebar of your website. You may need to activate Extension Manager first.

![image](https://user-images.githubusercontent.com/7662236/153754917-3eb9ea67-ebda-47c5-85d1-9cf83b0b8162.png)

Scroll down until you see the Title Fix extension, and hit "Activate".

![image](https://user-images.githubusercontent.com/7662236/153754968-2f06e2fb-55ea-4b9d-82a1-52a110456509.png)

**Comment by jimsax** [comment]
Many thanks sybrew that explains it so well, now fixed.
