### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by e11productions** [sybrew/The-SEO-Framework-Extension-Manager#6]
**Describe the bug**
When the plugin is active, we get this error: ///wp-content/plugins/the-seo-framework-extension-manager/inc/classes/core.class.php on line 572

**To Reproduce**
1. Go to plugins
2. Click on The-SEO-Framework-Extension-Manager
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sybrew** [comment]
I believe there might have been a faulty transaction in the plugin files. It isn't common, but it can occur.

As there's no further information gathered, I'm closing this.
