### ISSUE TITLE
1.5.3 to 2.0 upgrade white page

### ISSUE THREAD

**Issue by davvidp** [sybrew/The-SEO-Framework-Extension-Manager#8]
upgrading the plugin to 2.0 causes blank white page on the settings page
i even deleted 1.5.3 then installed 2.0 but still getting blank white page on the settings page

cheers

**Comment by sybrew** [comment]
Thanks for opening the issue @davvidp!

Could you enable `WP_DEBUG` in `wp-config.php`? The constant should look like this:
```php
define( 'WP_DEBUG', true );
```

When that's enabled, you should see an error code instead of a white page. Could you forward that error? Cheers!

**Comment by sybrew** [comment]
If you're still finding issues, please try reinstalling the plugin. If that doesn't work, feel free to follow up.

I'm closing this issue as GitHub's traffic insights imply this issue isn't occurring on other sites.
