### ISSUE TITLE
2.6.3 Changelog Link on website

### ISSUE THREAD

**Issue by advwebin** [sybrew/The-SEO-Framework-Extension-Manager#80]
**Describe the bug**
The link to Articles at version 2.3.0 is going to transport, instead of articles. Minor issue.

**Expected behavior**
https://theseoframework.com/extensions/articles/#changelog

**Screenshots**
<img width="332" alt="Screenshot 2023-11-04 at 12 04 47" src="https://github.com/sybrew/The-SEO-Framework-Extension-Manager/assets/90175055/f20434dd-4fbc-43de-9ea9-b4eed0ad309b">

**Additional context**
Waiting on TSF 5.0, Any release date to be expected?

**Comment by sybrew** [comment]
Fixed. Thanks for notifying me.

TSF v5.0's release is scheduled in about 3 weeks.
