### ISSUE TITLE
Extension manager don't work on free subscription

### ISSUE THREAD

**Issue by entumas** [sybrew/The-SEO-Framework-Extension-Manager#9]
Hi!

Extension manager don't work in free subscription, none of the 4 free extensions are activated by clicking on the Activate button, nothing just happens.

Thanks

**Comment by sybrew** [comment]
Hi!

Not even a notification? That means the JS files aren't loaded and, as such, there's a plugin conflict that causes a crash at the end of the HTML document of the page.

Could you try deactivating other plugins until it works, and note, through deduction, which plugin caused it? Thanks!

**Comment by entumas** [comment]
Hi!

There are no errors in the console, even disabling all plugins the error persists.
This happens to me from the last versions of EM (since the note of the new payment policy appeared), before it worked without problem.

Is there any other way that I can activate the extensions I need?
(AMP, Incognito, Origin)

Thanks.

**Comment by entumas** [comment]
Deactivating JS worked for me Sybrew, many thanks!

Another question: Are the premium versions paid annually? Are they multi-domain or single domain?

Thanks

**Comment by sybrew** [comment]
Great! It's not a permanent solution, so if you're able to provide additional details on this issue, please do 😃 I'm closing this issue for now, and await reports from other users, too.

A premium subscription is renewed every year, and you can cancel at any time. One site equals one WordPress installation or one multisite domain.
