### ISSUE TITLE
Only one sitemap.xml with WPML?

### ISSUE THREAD

**Issue by henktd** [sybrew/The-SEO-Framework-Extension-Manager#94]
In the documentation I read the following: 

If your site has multiple languages (e.g., using WPML), ensure that each language has its own sitemap, and that these are listed or linked correctly in your primary sitemap.

I'm using WPML to make two languages available on our website, NL and EN. How can I see these sitemaps?

Currently, I only see https://simmelink.nl/sitemap.xml

Thanks for your help.

**Comment by sybrew** [comment]
Goedemorgen!

If you remove the `robots.txt` file from your website's root folder, you'll get the automated (virtual) robots.txt output.
With that, you should see more sitemaps available, annotated by additional `sitemap:` links. Search engines can use these links to automatically find the sitemaps.

However, in your case, there appears to be a server misconfiguration in NGINX for dynamical `.xml` parsing, allowing only the sitemap's output on specific URLs.

We can bypass that restriction by using something like `.xmla` instead. 
We'll then find that there's also a sitemap being created for the English site: https://simmelink.nl/en/sitemap.xmla.

Still, I recommend resolving the `.xml` restriction. NGINX should not treat them like static files when using WordPress.

If you're unable to resolve the restriction, you could still opt for the alternative `.xmla` URLs and submit those manually at [Google Search Console](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap) and [Bing Webmasters](https://www.bing.com/webmasters/help/Sitemaps-3b5cf6ed).

P.S. I also recommend disabling `SCRIPT_DEBUG`, which appears to be set at `wp-config.php`.

**Comment by henktd** [comment]
Hoi Sybren,
Dank voor dit mooie antwoord. Ik ga er straks meteen mee aan de slag.

Overigens heb je mooie plug-in geschreven. Vandaag ga ik er verder naar kijken om het dan helemaal uit te zoeken.

Gr Henk

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Sybre Waaijer ***@***.***>
Verzonden: Sunday, November 3, 2024 9:42:14 AM
Aan: sybrew/The-SEO-Framework-Extension-Manager ***@***.***>
CC: Henk ten Dolle ***@***.***>; Author ***@***.***>
Onderwerp: Re: [sybrew/The-SEO-Framework-Extension-Manager] Only one sitemap.xml with WPML? (Issue #94)

U ontvangt niet vaak e-mail van ***@***.*** Ontdek waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Goedemorgen!

If you remove the robots.txt file from your website's root folder, you'll get the automated (virtual) robots.txt output.
With that, you should see more sitemaps available, annotated by additional sitemap: links. Search engines can use these links to automatically find the sitemaps.

However, in your case, there appears to be a server misconfiguration in NGINX for dynamical .xml parsing, allowing only the sitemap's output on specific URLs.

We can bypass that restriction by using something like .xmla instead.
We'll then find that there's also a sitemap being created for the English site: https://simmelink.nl/en/sitemap.xmla.

Still, I recommend resolving the .xml restriction. NGINX should not treat them like static files when using WordPress.

If you're unable to resolve the restriction, you could still opt for the alternative .xmla URLs and submit those manually at Google Search Console<https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap> and Bing Webmasters<https://www.bing.com/webmasters/help/Sitemaps-3b5cf6ed>.

P.S. I also recommend disabling SCRIPT_DEBUG, which appears to be set at wp-config.php.

**Comment by sybrew** [comment]
Graag gedaan, Henk! 😊 Mooi dat je het probleem hebt kunnen oplossen.
